//------------------------------------------------------------------------------
// <auto-generated>
//   此代码由 DataTableGenerator 工具自动生成，请勿手动修改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using GameFramework.DataTable;

namespace GameMain
{
    /// <summary>
    /// Sound 数据表行。
    /// </summary>
    public sealed class DRSound : IDataRow
    {
                /// <summary>名称</summary>
        public string Name { get; private set; }

        /// <summary>资源名称</summary>
        public string AssetName { get; private set; }

        /// <summary>优先级（默认0，128最高，-128最低）</summary>
        public int Priority { get; private set; }

        /// <summary>是否循环</summary>
        public bool Loop { get; private set; }

        /// <summary>音量（0~1）</summary>
        public float Volume { get; private set; }

        /// <summary>声音空间混合量（0为2D，1为3D，中间值混合效果）</summary>
        public float SpatialBlend { get; private set; }

        /// <summary>声音最大距离</summary>
        public float MaxDistance { get; private set; }

        public int Id { get; private set; }

        

        public bool ParseDataRow(string dataRowString, object userData)
        {
            string[] columnStrings = dataRowString.Split('\t');
                        Id = int.Parse(columnStrings[1]);
            Name = columnStrings[3];
            AssetName = columnStrings[4];
            Priority = int.Parse(columnStrings[5]);
            Loop = bool.Parse(columnStrings[6]);
            Volume = float.Parse(columnStrings[7]);
            SpatialBlend = float.Parse(columnStrings[8]);
            MaxDistance = float.Parse(columnStrings[9]);
            return true;
        }

        public bool ParseDataRow(byte[] dataRowBytes, int startIndex, int length, object userData)
        {
            using var stream = new MemoryStream(dataRowBytes, startIndex, length, false);
            using var reader = new BinaryReader(stream, System.Text.Encoding.UTF8);
                        Id = reader.Read7BitEncodedInt32();
            Name = reader.ReadString();
            AssetName = reader.ReadString();
            Priority = reader.Read7BitEncodedInt32();
            Loop = reader.ReadBoolean();
            Volume = reader.ReadSingle();
            SpatialBlend = reader.ReadSingle();
            MaxDistance = reader.ReadSingle();
            return true;
        }
    }
}
