//------------------------------------------------------------------------------
// <auto-generated>
//   此代码由 DataTableGenerator 工具自动生成，请勿手动修改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using GameFramework.DataTable;

namespace GameMain
{
    /// <summary>
    /// UIForm 数据表行。
    /// </summary>
    public sealed class DRUIForm : IDataRow
    {
                /// <summary>名称</summary>
        public string Name { get; private set; }

        /// <summary>资源名称</summary>
        public string AssetName { get; private set; }

        /// <summary>界面组名称</summary>
        public string UIGroupName { get; private set; }

        /// <summary>是否允许多个界面实例</summary>
        public bool AllowMultiInstance { get; private set; }

        /// <summary>是否隐藏被其覆盖的界面</summary>
        public bool PauseCoveredUIForm { get; private set; }

        public int Id { get; private set; }

        

        public bool ParseDataRow(string dataRowString, object userData)
        {
            string[] columnStrings = dataRowString.Split('\t');
                        Id = int.Parse(columnStrings[1]);
            Name = columnStrings[3];
            AssetName = columnStrings[4];
            UIGroupName = columnStrings[5];
            AllowMultiInstance = bool.Parse(columnStrings[6]);
            PauseCoveredUIForm = bool.Parse(columnStrings[7]);
            return true;
        }

        public bool ParseDataRow(byte[] dataRowBytes, int startIndex, int length, object userData)
        {
            using var stream = new MemoryStream(dataRowBytes, startIndex, length, false);
            using var reader = new BinaryReader(stream, System.Text.Encoding.UTF8);
                        Id = reader.Read7BitEncodedInt32();
            Name = reader.ReadString();
            AssetName = reader.ReadString();
            UIGroupName = reader.ReadString();
            AllowMultiInstance = reader.ReadBoolean();
            PauseCoveredUIForm = reader.ReadBoolean();
            return true;
        }
    }
}
