//------------------------------------------------------------------------------
// <auto-generated>
//   此代码由 DataTableGenerator 工具自动生成，请勿手动修改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using GameFramework.DataTable;

namespace GameMain
{
    /// <summary>
    /// UITranslation 数据表行。
    /// </summary>
    public sealed class DRUITranslation : IDataRow
    {
                /// <summary>名称</summary>
        public string Name { get; private set; }

        /// <summary>中文简体</summary>
        public string ChineseSimplified { get; private set; }

        /// <summary>英语</summary>
        public string English { get; private set; }

        /// <summary>中文繁体</summary>
        public string ChineseTraditional { get; private set; }

        /// <summary>韩语</summary>
        public string Korean { get; private set; }

        public int Id { get; private set; }

        

        public bool ParseDataRow(string dataRowString, object userData)
        {
            string[] columnStrings = dataRowString.Split('\t');
                        Id = int.Parse(columnStrings[1]);
            Name = columnStrings[3];
            ChineseSimplified = columnStrings[4];
            English = columnStrings[5];
            ChineseTraditional = columnStrings[6];
            Korean = columnStrings[7];
            return true;
        }

        public bool ParseDataRow(byte[] dataRowBytes, int startIndex, int length, object userData)
        {
            using var stream = new MemoryStream(dataRowBytes, startIndex, length, false);
            using var reader = new BinaryReader(stream, System.Text.Encoding.UTF8);
                        Id = reader.Read7BitEncodedInt32();
            Name = reader.ReadString();
            ChineseSimplified = reader.ReadString();
            English = reader.ReadString();
            ChineseTraditional = reader.ReadString();
            Korean = reader.ReadString();
            return true;
        }
    }
}
